# Generated by Django 4.1.5 on 2023-01-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geeks_field',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
