# Generated by Django 4.1.5 on 2023-01-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_geeks_field_post_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geeks_field',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
